tag: project2
neural-network: # List of neural networks
  - type: 1x1_net  # Name of the neural network (same used in the --network option)
    config: # Configuration of the neural network
      neurons_per_layer:
        - 1
      activations:
        - logistic
      loss_function: square_error
      learning_rate: 5
      epochs: 5000
      print_every: 500
  - type: 2x1_net  # Name of the neural network (same used in the --network option)
    config:  # Configuration of the neural network
      neurons_per_layer:
        - 2
        - 1
      activations:
        - logistic
        - logistic
      loss_function: square_error
      learning_rate: 5
      epochs: 5000
      print_every: 500
  - type: 2x2_net  # Name of the neural network (same used in the --network option)
    config:  # Configuration of the neural network
      neurons_per_layer:
        - 2
        - 2
      activations:
        - logistic
        - logistic
      loss_function: cross_entropy
      learning_rate: 0.5
      epochs: 100
      print_every: 100
dataset: # List of datasets
  - type: class_example  # Name of the dataset (same used in the --dataset option)
    config: # Configuration of the dataset
      inputs: # Inputs from the class example
        - 0.05
        - 0.1
      desired_outputs: # Desired outputs from the class example
        - 0.01
        - 0.99
      weights: # 2x2x3 matrix (layer x neuron x weights+bias)
        - - - 0.15
            - 0.20
            - 0.35
          - - 0.25
            - 0.30
            - 0.35
        - - - 0.40
            - 0.45
            - 0.60
          - - 0.50
            - 0.55
            - 0.60
  - type: xor  # Name of the dataset (same used in the --dataset option)
    config: # Configuration of the dataset
      inputs: # Inputs to the network
        - - 0
          - 0
        - - 0
          - 1
        - - 1
          - 0
        - - 1
          - 1
      outputs: # Desired outputs
        - 0
        - 1
        - 1
        - 0
  - type: and  # Name of the dataset (same used in the --dataset option)
    config: # Configuration of the dataset
      inputs: # Inputs to the network
        - - 0
          - 0
        - - 0
          - 1
        - - 1
          - 0
        - - 1
          - 1
      outputs: # Desired outputs
        - 0
        - 0
        - 0
        - 1
